name: Deploy to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "ritik254chail@gmail.com"
          git config --global user.name "GitHub Action"
          git clone https://USER:$HF_TOKEN@huggingface.co/spaces/ritikchail/pdf_analyzer hf_space
          cd hf_space
          # Copy only contents, not the parent folder
          cp -r ../{app.py,processing.py,session_manager.py,requirements.txt,README.md} .
          git add .
          git -c user.email="actions@github.com" -c user.name="GitHub Action" commit -m "Update from GitHub"
          git push
