name: Deploy to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "ritik254chail@gmail.com"
          git config --global user.name "GitHub Action"
          git clone https://USER:$HF_TOKEN@huggingface.co/spaces/ritikchail/pdf_analyzer
          cd pdf_analyzer
          rm -rf *  # Nuclear cleanup
          cp -r ../* .
          git add -A
          git commit -m "Force update from GitHub" --allow-empty
          git push --force
