name: Deploy to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir temp_dir && cd temp_dir
          git init
          git remote add origin https://USER:$HF_TOKEN@huggingface.co/spaces/ritikchail/pdf_analyzer
          git pull origin main --allow-unrelated-histories --force
          git rm -r * || echo "No files to delete"
          cp ../app.py ../processing.py ../session_manager.py ../requirements.txt .

          # Force push
          git add .
          git commit -m "Overwrite with core files" --allow-empty
          git push origin main --force
